name: Python CI

on:
  push:
    branches: [ main, Siddhi ]
  pull_request:
    branches: [ main, Siddhi ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest pytest-cov

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests with coverage
      run: |
        pytest -q \
          --maxfail=1 \
          --disable-warnings \
          --cov=. --cov-report=xml --cov-report=term-missing \
          test_01_ocr.py test_enhance.py test_commodity.py test_heirarchical.py test_rateofduty.py test_tariffpara.py test-pipeline.py
      continue-on-error: false

    - name: Upload coverage.xml
      if: always() && hashFiles('coverage.xml') != ''
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml
        path: coverage.xml

    - name: Upload pytest JUnit report (if generated)
      if: always() && hashFiles('pytest.xml') != ''
      uses: actions/upload-artifact@v4
      with:
        name: pytest-junit
        path: pytest.xml

    - name: Run pipeline smoke test
      run: |
        python pipeline.py --help || true
